  
version: 0.6.{build}

branches:
  only:
  - master
build:
  verbosity: minimal
  
# Do not build on tags
skip_tags: true

environment:

  git_token:
    secure: gQgtJwYFLPs5DTavpysYlG/8LDOgg2DXlK15eupG2epdngqyp7f3Av0/WnmudbO/

  matrix:

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019"
      ARCH: "x64"
      CONFIG: Release
      PYVER: 39
      PYLOC: "C:/Python39-x64/python.exe"
      PYSTACK: "3.9"
      PYFULLVERSION: "3.9.0"
      PYDOCRUN: "true"

matrix:
  fast_finish: true

stack:
  python %PYSTACK%
  
# actual build
build_script:
  
  #  # deploy test docs
  - ps: |
      if ( $env:APPVEYOR_REPO_COMMIT_MESSAGE -like "*(test)*" )
      {
        if ( $env:PYDOCRUN -like "*true*" )
        {
          git config --global credential.helper store
          Add-Content -Path "$HOME\.git-credentials" -Value "https://$($env:git_token):x-oauth-basic@github.com`n" -NoNewline
          git config --global user.email "prestoncothren@yahoo.com"
          git config --global user.name "Preston Cothren"
          cd C:\projects
          git clone -b gh-pages --single-branch "https://github.com/Pcothren/dpg-test-py-docs"
          cd dpg-test-py-docs
          C:\Python39-x64\python.exe -m pip install -i https://test.pypi.org/simple/ dearpygui
          C:\Python39-x64\python.exe -m pip install pdoc3
          C:\Python39-x64\python.exe -m pdoc --html dearpygui -f
          C:\Python39-x64\python.exe html_script.py
          git commit -a -m "Update Docs for $env:APPVEYOR_BUILD_VERSION"
          git push origin gh-pages -q
        }
      }
